spring:
  profiles:
    active: default
  flyway:
    enabled: false # Disable Flyway for now. I'm going to enable only in production and dev (staging) profile
  config:
    import: optional:classpath:.env.properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: ${GOOGLE_OAUTH2_SCOPE}
        
#      resourceserver:
#        jwt:
#          issuer-uri: "http://localhost:8080/auth/realms/hobbie-realm"
#          jwk-set-uri: "http://localhost:8080/auth/realms/hobbie-realm/protocol/openid-connect/certs"
server:
  port: 8081

hobbie-addons:
  issuers:
    - uri: "https://accounts.google.com"
    - uri: "http://localhost:8080/realms/hobbie-realm"
