spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: ${GOOGLE_OAUTH2_SCOPE}
amazon:
  s3:
    access-key: ${AMAZON_S3_ACCESS_KEY}
    secret-key: ${AMAZON_S3_SECRET_KEY}
    bucket-name: ${AMAZON_S3_BUCKET_NAME}
    region: ${AMAZON_S3_REGION}

hobbie-addons:
  issuers:
    - uri: "https://accounts.google.com"
    - uri: ${KEYCLOAK_URI}
hobbie:
  authentication:
    keycloak:
      uri-scheme: ${KEYCLOAK_URI}
      client-id: ${KEYCLOAK_CLIENT_ID}
      auth-client-id: ${KEYCLOAK_AUTH_CLIENT_ID}
      realm: ${KEYCLOAK_REALM}
      secret: ${KEYCLOAK_SECRET}
      server-url: ${KEYCLOAK_SERVER_URL}