CREATE SEQUENCE IF NOT EXISTS event_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS join_request_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS tag_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE event
(
    id          BIGINT  NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    capacity    INTEGER NOT NULL,
    start_date  TIMESTAMP WITHOUT TIME ZONE,
    end_date    TIMESTAMP WITHOUT TIME ZONE,
    latitude    FLOAT,
    longitude   FLOAT,
    thumbnail   VARCHAR(255),
    active      BOOLEAN NOT NULL,
    admin_id    BIGINT,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE event_categories
(
    event_id      BIGINT NOT NULL,
    categories_id BIGINT NOT NULL,
    CONSTRAINT pk_event_categories PRIMARY KEY (event_id, categories_id)
);

CREATE TABLE event_participants
(
    participant_events_id BIGINT NOT NULL,
    participants_id       BIGINT NOT NULL,
    CONSTRAINT pk_event_participants PRIMARY KEY (participant_events_id, participants_id)
);

CREATE TABLE join_request
(
    id           BIGINT NOT NULL,
    player_id    BIGINT,
    event_id     BIGINT,
    request_time TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(255),
    CONSTRAINT pk_joinrequest PRIMARY KEY (id)
);

CREATE TABLE player
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    avatar          VARCHAR(255),
    match_latitude  FLOAT,
    match_longitude FLOAT,
    radius          DECIMAL,
    birth_date      date,
    CONSTRAINT pk_player PRIMARY KEY (id)
);

CREATE TABLE player_interests
(
    player_id    BIGINT NOT NULL,
    interests_id BIGINT NOT NULL,
    CONSTRAINT pk_player_interests PRIMARY KEY (player_id, interests_id)
);

CREATE TABLE tag
(
    id   BIGINT NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_ADMIN FOREIGN KEY (admin_id) REFERENCES player (id);

ALTER TABLE join_request
    ADD CONSTRAINT FK_JOINREQUEST_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE join_request
    ADD CONSTRAINT FK_JOINREQUEST_ON_PLAYER FOREIGN KEY (player_id) REFERENCES player (id);

ALTER TABLE event_categories
    ADD CONSTRAINT fk_evecat_on_event FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE event_categories
    ADD CONSTRAINT fk_evecat_on_tag FOREIGN KEY (categories_id) REFERENCES tag (id);

ALTER TABLE event_participants
    ADD CONSTRAINT fk_evepar_on_event FOREIGN KEY (participant_events_id) REFERENCES event (id);

ALTER TABLE event_participants
    ADD CONSTRAINT fk_evepar_on_player FOREIGN KEY (participants_id) REFERENCES player (id);

ALTER TABLE player_interests
    ADD CONSTRAINT fk_plaint_on_player FOREIGN KEY (player_id) REFERENCES player (id);

ALTER TABLE player_interests
    ADD CONSTRAINT fk_plaint_on_tag FOREIGN KEY (interests_id) REFERENCES tag (id);