name: Run tests on pull requests

on:
  workflow_dispatch:
jobs:
  test:
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
      keycloak:
        image: quay.io/keycloak/keycloak:22.0.5
        env:
          JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
          KC_DB_PASSWORD: postgres
          KC_DB_URL: jdbc:postgresql://postgres/keycloak
          KC_DB_USERNAME: postgres
          KC_HEALTH_ENABLED: 'true'
          KC_HTTP_ENABLED: 'true'
          KC_METRICS_ENABLED: 'true'
          KC_PROXY: reencrypt
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
          - "8180:8080"
          - "8787:8787" # debug port
    runs-on: ubuntu-latest
    container: openjdk:17-jdk

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        env:
          DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          KEYCLOAK_URL: http://keycloak:8080
          KEYCLOAK_USERNAME: admin
          KEYCLOAK_PASSWORD: admin
        run: mvn -B clean test