name: Run tests on pull requests

on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container: openjdk:17-jdk

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5

      - name: Run tests
        run: mvn -B clean test

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml -DskipTests

#  build:
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#
#      - uses: akhileshns/heroku-deploy@v3.12.14
#        with:
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#          heroku_email: ${{ secrets.HEROKU_EMAIL }}
