name: Only run tests on pull requests

on:
  pull_request:
    branches:
      - main
      - development
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@4.4
        with:
          maven-version: 3.8.3

      - name: Run Tests
        run: mvn clean install

