name: Only run tests on pull requests

on:
  pull_request:
    branches:
      - main
      - development
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'maven'

      - name: Run Tests
        run: mvn clean test

